#App
server.port=8080
spring.application.name=social-networking-backend

#DATABASE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/social_networking?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

#JPA / HIBERNATE
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# PASSWORD POLICY CONFIG
app.security.password.min-length=8
app.security.password.require-lowercase=true
app.security.password.require-number=true
app.security.password.require-special=true
app.security.password.special-chars=!@#$%^&*(),.?":{}|<>

#JWT
jwt.secret=${JWT_SECRET_KEY}
#Expiration time (minutes)
jwt.access.expiration_time=${JWT_ACCESS_EXPIRATION_TIME}
jwt.refresh.expiration_time=${JWT_REFRESH_EXPIRATION_TIME}

cron.deleteExpiredTokenBlacklist=

#Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#Swagger
springdoc.api-docs.enabled=true
springdoc.packagesToScan=com.example.socialnetworkingbackend.controller
springdoc.pathsToMatch=/**

#Infor Mail Send OTP
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

#Info Admin
admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}
admin.lastName=${ADMIN_LASTNAME}
admin.firstName=${ADMIN_FIRSTNAME}
admin.email=${ADMIN_EMAIL:admin@example.com}

spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST_SIZE:400MB}
spring.servlet.multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE:400MB}

#Redis cloud
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DATABASE}